name: Pipeline Desafio CI/CD
run-name: Pipeline de CI/CD executada por ${{ github.actor }} em ${{ github.run_number }}

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.300'
      - name: Execução do comando build
        working-directory: ./src
        run: dotnet build Review-Filmes.sln
  
  release:
    name: Criação de release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Obtendo o código do projeto
        uses: actions/checkout@v4
      - name: Fazendo a autenticação no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build e Push da imagem Docker
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./src
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: 
            clevernvs/desafio-devops-cicd:latest
            clevernvs/desafio-devops-cicd:v${{ github.run_number }}